# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: function_context.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x66unction_context.proto\x12\x12\x62lackfyre.protobuf\"\x84\x02\n\x0f\x46unctionContext\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rstart_address\x18\x02 \x01(\x04\x12\x13\n\x0b\x65nd_address\x18\x03 \x01(\x04\x12\x10\n\x08is_thunk\x18\x04 \x01(\x08\x12\x11\n\tproc_type\x18\x05 \x01(\r\x12\x14\n\x0csegment_name\x18\x06 \x01(\t\x12G\n\x18\x62\x61sic_block_context_list\x18\x07 \x03(\x0b\x32%.blackfyre.protobuf.BasicBlockContext\x12\x1a\n\x12total_instructions\x18\x08 \x01(\x04\x12\x17\n\x0f\x64\x65\x63ompiled_code\x18\t \x01(\t\"\x9c\x01\n\x11\x42\x61sicBlockContext\x12\x15\n\rstart_address\x18\x01 \x01(\x04\x12\x13\n\x0b\x65nd_address\x18\x02 \x01(\x04\x12\x11\n\tproc_type\x18\x03 \x01(\r\x12H\n\x18instruction_context_list\x18\x04 \x03(\x0b\x32&.blackfyre.protobuf.InstructionContext\"M\n\x12InstructionContext\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x04\x12\x14\n\x0copcode_bytes\x18\x02 \x01(\x0c\x12\x10\n\x08mnemonic\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'function_context_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FUNCTIONCONTEXT']._serialized_start=47
  _globals['_FUNCTIONCONTEXT']._serialized_end=307
  _globals['_BASICBLOCKCONTEXT']._serialized_start=310
  _globals['_BASICBLOCKCONTEXT']._serialized_end=466
  _globals['_INSTRUCTIONCONTEXT']._serialized_start=468
  _globals['_INSTRUCTIONCONTEXT']._serialized_end=545
# @@protoc_insertion_point(module_scope)
