# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pe_header.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpe_header.proto\x12\x12\x62lackfyre.protobuf\"\x8f\x05\n\x08PEHeader\x12\x12\n\ntime_stamp\x18\x01 \x01(\x04\x12\x15\n\rsize_of_image\x18\x02 \x01(\x04\x12\x1e\n\x16\x61\x64\x64ress_of_entry_point\x18\x03 \x01(\x04\x12 \n\x18size_of_initialized_data\x18\x04 \x01(\x04\x12\x14\n\x0csize_of_code\x18\x05 \x01(\x04\x12\x18\n\x10size_of_raw_data\x18\x06 \x01(\x04\x12\x10\n\x08\x63hecksum\x18\x07 \x01(\x04\x12\x1b\n\x13\x64ll_characteristics\x18\x08 \x01(\x04\x12\x1a\n\x12number_of_sections\x18\t \x01(\x04\x12\x1c\n\x14major_linker_version\x18\n \x01(\x04\x12\x1b\n\x13major_image_version\x18\x0b \x01(\x04\x12\"\n\x1asize_of_uninitialized_data\x18\x0c \x01(\x04\x12\x14\n\x0c\x62\x61se_of_code\x18\r \x01(\x04\x12\x1c\n\x14minor_linker_version\x18\x0e \x01(\x04\x12\x17\n\x0fsize_of_headers\x18\x0f \x01(\x04\x12&\n\x1emajor_operating_system_version\x18\x10 \x01(\x04\x12\x1d\n\x15size_of_stack_reserve\x18\x11 \x01(\x04\x12\x16\n\x0e\x66ile_alignment\x18\x12 \x01(\x04\x12\x1b\n\x13minor_image_version\x18\x13 \x01(\x04\x12\x1f\n\x17major_subsystem_version\x18\x14 \x01(\x04\x12\x1c\n\x14size_of_stack_commit\x18\x15 \x01(\x04\x12\x1c\n\x14size_of_heap_reserve\x18\x16 \x01(\x04\x12\x16\n\x0ent_header_name\x18\x17 \x01(\tB\x14\x42\x12PEHeaderOuterClassb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pe_header_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\022PEHeaderOuterClass'
  _globals['_PEHEADER']._serialized_start=40
  _globals['_PEHEADER']._serialized_end=695
# @@protoc_insertion_point(module_scope)
